name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win32-x64
          - os: ubuntu-18.04
            platform: linux-x64
          - os: ubuntu-18.04
            platform: linux-arm64
          - os: macos-latest
            platform: darwin-x64
          - os: macos-latest
            platform: darwin-arm64
    steps:
    - uses: actions/checkout@v3
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - if: matrix.platform == 'linux-arm64'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    - run: luamake -platform ${{ matrix.platform }} -luajit on
    - run: npm install -g vsce ovsx
    - if: matrix.platform != 'win32-x64'
      run: |
        cd publish
        npx vsce publish --target ${{ matrix.platform }} -p ${{ secrets.VSCE_KEY }}
        npx ovsx publish --target ${{ matrix.platform }} -p ${{ secrets.OVSX_KEY }}
      continue-on-error: true
    - if: matrix.platform == 'win32-x64'
      run: |
        cd publish
        npx vsce publish --target win32-x64 -p ${{ secrets.VSCE_KEY }}
        npx vsce publish --target win32-ia32 -p ${{ secrets.VSCE_KEY }}
        npx ovsx publish --target win32-x64 -p ${{ secrets.OVSX_KEY }}
        npx ovsx publish --target win32-ia32 -p ${{ secrets.OVSX_KEY }}
      continue-on-error: true
